export const gameValues = {
    "01": "Line Break",
    "02": "End Marker",
    "03": "Causes all text before it to be dropped from the final, raw output placed in the game. Allows the developers to add message IDs to their files, as well as comments explaining each message's context. It's unknown what happens if you attempt to use this in the game.",
    "04": "Box Break; begin next message box.",
    "05": "Color the following text with color xxxx.",
    "06": "Shift text that follows it xx pixels to the right.",
    "07": "Go to (follow up with) Message ID xxxx.",
    "08": "Enable instantaneous text.",
    "09": "Disable instantaneous text.",
    "0A": "Keep message box opened; no reaction to buttons. Used in shop item descriptions.",
    "0B": "Trigger an event? Used in minigame text, shop text, sidequest text, fairy fountains, and when being rewarded by uncursed skulltulas, among others. Used to indicate receiving something, perhaps? Appears to always occur before 8170 (End Marker).",
    "0C": "Box Break with delay; wait xx visual frames before next message box.",
    "0D": "(Unused?) Wait for button press, continue in same box or line.",
    "0E": "Fade out after waiting xx visual frames?",
    "0F": "Print the player's name.",
    "10": "Initialize Ocarina playing.",
    "11": "(Unused?) Fade out and wait; ignore following text. iQue leak claims it's used for 'STAFF' (staff credits?) in the English text documentation. No equivalent code appears to exist in the Japanese text documentation.",
    "12": "Play sound effect xxxx.",
    "13": "Display icon xx.",
    "14": "Set text speed to xx. (Delay printing each character by xx frames.)",
    "15": "Set message background to xxxxxx. Values unknown.",
    "16": "Print Marathon time.",
    "17": "Print Race time.",
    "18": "Print number of points.[for what?]",
    "19": "Print number of Gold Skulltulas collected.",
    "1A": "Prevent the following text from being skipped by the B button.",
    "1B": "Initialize a two-choice selection.",
    "1C": "Initialize a three-choice selection.",
    "1D": "Print the length (JP)/weight (non-JP) of the caught fish.",
    "1E": "Print various highscore values.",
    "1F": "Print the in-game world time."
  };
  
  